#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\ownergroups\ownergroupConst.py
MEMBERSHIP_TYPE_NONE = -1
MEMBERSHIP_TYPE_MEMBER = 0
MEMBERSHIP_TYPE_MANAGER = 1
MEMBERSHIP_TYPE_ADMIN = 2
MEMBERSHIP_TYPE_EXCLUDED = 3
GROUP_CREATED = 1
GROUP_MEMBER_ADDED = 2
GROUP_MEMBERTYPE_CHANGED = 3
GROUP_MEMBER_REMOVED = 4
GROUP_NAME_CHANGED = 5
GROUP_DESCRIPTION_CHANGED = 6
GROUP_DELETED = 7
GROUP_CHANGED_FOR_LISTENER = 8
PUBLIC_MEMBER_ID = 0
NO_GROUP_ID = 0
MAX_NUMBER_OF_GROUPS_TO_MANAGE = 1000
