#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\entosis\entosisConst.py
from carbon.common.lib.const import HOUR
EVENT_TYPE_TCU_DEFENSE = 1
EVENT_TYPE_IHUB_DEFENSE = 2
EVENT_TYPE_STATION_DEFENSE = 3
EVENT_TYPE_STATION_FREEPORT = 4
EVENTS_TYPES_WITH_OCCUPANCY_BONUS = (EVENT_TYPE_TCU_DEFENSE, EVENT_TYPE_IHUB_DEFENSE, EVENT_TYPE_STATION_DEFENSE)
EVENT_DEBUG_NAMES_BY_TYPE = {EVENT_TYPE_TCU_DEFENSE: 'TCU Defense',
 EVENT_TYPE_IHUB_DEFENSE: 'IHub Defense',
 EVENT_TYPE_STATION_DEFENSE: 'Station Defense',
 EVENT_TYPE_STATION_FREEPORT: 'Station Freeport'}
EVENT_TYPE_TCU_DEFENSE = 1
EVENT_TYPE_IHUB_DEFENSE = 2
EVENT_TYPE_STATION_DEFENSE = 3
EVENT_TYPE_STATION_FREEPORT = 4
STRUCTURE_SCORE_UPDATED = 0
STRUCTURES_UPDATED = 1
CHANGE_PRIMETIME_DELAY = 48 * HOUR
