#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\localization\propertyHandlers\__init__.py
import characterPropertyHandler
import characterPropertyHandler
import itemPropertyHandler
import locationPropertyHandler
import npcOrganizationPropertyHandler
import numericPropertyHandler
import timeIntervalPropertyHandler
