#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\cfg.py
from carbon.common.script.sys.cfg import Recordset
from carbon.common.script.sys.cfg import Row
from carbon.common.script.sys.cfg import Worldspaces
from eve.common.script.sys.eveCfg import AllShortNames
from eve.common.script.sys.eveCfg import Billtype
from eve.common.script.sys.eveCfg import CrpTickerNames
from eve.common.script.sys.eveCfg import DgmAttribute
from eve.common.script.sys.eveCfg import DgmEffect
from eve.common.script.sys.eveCfg import DgmUnit
from eve.common.script.sys.eveCfg import EveOwners
from eve.common.script.sys.eveCfg import Faction
from eve.common.script.sys.eveCfg import InvMetaGroup
from eve.common.script.sys.eveCfg import MapCelestialDescription
from eve.common.script.sys.eveCfg import Position
from eve.common.script.sys.eveCfg import Race
from eve.common.script.sys.eveCfg import RamActivity
from eve.common.script.sys.eveCfg import RamCompletedStatus
from eve.common.script.sys.eveCfg import Schematic
from eve.common.script.sys.eveCfg import CfgFsdDustIcons
from eve.common.script.sys.eveCfg import CfgIcons
from eve.common.script.sys.eveCfg import CfgSounds
from eve.common.script.sys.eveCfg import CfgInvcontrabandFactionsByType
from eve.common.script.sys.eveCfg import CfgShiptypes
from eve.common.script.sys.eveCfg import CfgAverageMarketPrice
