#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\cqscreentemplates.py
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import AuraMessage
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import CareerAgent
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import CharacterInfo
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import CloneStatus
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import FullscreenVideo
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import Incursion
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import Plex
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import RacialEpicArc
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import SOV
from eve.client.script.ui.station.captainsquarters.mainScreenTemplates import ShipExposure
