#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\eveCfg.py
from eve.common.script.sys.eveCfg import Constellation
from eve.common.script.sys.eveCfg import InvCategory
from eve.common.script.sys.eveCfg import InvGroup
from eve.common.script.sys.eveCfg import InvType
from eve.common.script.sys.eveCfg import OverviewDefault
from eve.common.script.sys.eveCfg import Region
from eve.common.script.sys.eveCfg import SolarSystem
from eve.common.script.sys.eveCfg import Standings
