#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\mathCommon.py
from carbon.common.script.util.mathCommon import BoundedRotateQuatByYaw
from carbon.common.script.util.mathCommon import CalcLinearIntpValue
from carbon.common.script.util.mathCommon import CalcScaledValueOverInterval
from carbon.common.script.util.mathCommon import CalculateShortestRotation
from carbon.common.script.util.mathCommon import ComposeMatrix
from carbon.common.script.util.mathCommon import CreateDirectionVectorFromYawAndPitchAngle
from carbon.common.script.util.mathCommon import CreateDirectionVectorFromYawAngle
from carbon.common.script.util.mathCommon import CreateOrthogonalVector
from carbon.common.script.util.mathCommon import DecomposeMatrix
from carbon.common.script.util.mathCommon import FloatCloseEnough
from carbon.common.script.util.mathCommon import GetDeltaAngleToFaceTarget
from carbon.common.script.util.mathCommon import GetLesserAngleBetweenYaws
from carbon.common.script.util.mathCommon import GetNewQuatToFacePos
from carbon.common.script.util.mathCommon import GetPitchAngleFromDirectionVector
from carbon.common.script.util.mathCommon import GetRandomHemisphereVector
from carbon.common.script.util.mathCommon import GetViewFrustumPlanes
from carbon.common.script.util.mathCommon import GetYawAndPitchAnglesDeg
from carbon.common.script.util.mathCommon import GetYawAndPitchAnglesRad
from carbon.common.script.util.mathCommon import GetYawAngleFromDirectionVector
from carbon.common.script.util.mathCommon import LineIntersectVerticalPlaneWithTwoPoints
from carbon.common.script.util.mathCommon import MatrixCloseEnough
from carbon.common.script.util.mathCommon import RandomVector
from carbon.common.script.util.mathCommon import RotateQuatByYaw
from carbon.common.script.util.mathCommon import TrinityMatrixCloseEnough
from carbon.common.script.util.mathCommon import VectorCloseEnough
