#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\timecurves.py
from carbon.client.script.util.timecurves import MaxLen
from carbon.client.script.util.timecurves import MaxLenF
from carbon.client.script.util.timecurves import PlaySounds
from carbon.client.script.util.timecurves import ReadCurves
from carbon.client.script.util.timecurves import ReadTimeAndSoundCurvesF
from carbon.client.script.util.timecurves import ReadTimeCurvesF
from carbon.client.script.util.timecurves import ResetTimeAndSoundCurves
from carbon.client.script.util.timecurves import ResetTimeAndSoundCurvesAndCuePoints
from carbon.client.script.util.timecurves import ResetTimeAndSoundCurvesF
from carbon.client.script.util.timecurves import ResetTimeCurves
from carbon.client.script.util.timecurves import ResetTimeCurvesF
from carbon.client.script.util.timecurves import ReverseTimeCurves
from carbon.client.script.util.timecurves import ReverseTimeCurvesF
from carbon.client.script.util.timecurves import ScaleTime
from carbon.client.script.util.timecurves import ScaleTimeF
from carbon.client.script.util.timecurves import SetCurveExtrapolation
from carbon.client.script.util.timecurves import SetCurveExtrapolationF
from carbon.client.script.util.timecurves import SetDuration
from carbon.client.script.util.timecurves import SetDurationF
