#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\ttimerutil.py
from carbon.common.script.util.ttimerutil import Callee
from carbon.common.script.util.ttimerutil import GetTimeMode
from carbon.common.script.util.ttimerutil import GetTimeModes
from carbon.common.script.util.ttimerutil import GetTimer
from carbon.common.script.util.ttimerutil import Resources
from carbon.common.script.util.ttimerutil import SetTimeMode
from carbon.common.script.util.ttimerutil import TaskletSnapshot
from carbon.common.script.util.ttimerutil import Timer
