#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\worldspaceCustomization.py
from eve.client.script.ui.station.worldspaceCustomization import ApplyWorldspaceCustomization
from eve.client.script.ui.station.worldspaceCustomization import MultiplyColorValue
from eve.client.script.ui.station.worldspaceCustomization import SetShaderMaterialValue
from eve.client.script.ui.station.worldspaceCustomization import UpdateCylendricalLights
from eve.client.script.ui.station.worldspaceCustomization import UpdateEnlightenTexture
from eve.client.script.ui.station.worldspaceCustomization import UpdateFlares
from eve.client.script.ui.station.worldspaceCustomization import UpdateShaderParameters
from eve.client.script.ui.station.worldspaceCustomization import UpdateSpotPointLights
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import DEFAULT_GALLENTE
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import QUAFE_OWNER
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import themeSettings
