#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\structures\const.py
STATE_UNKNOWN = 0
STATE_UNANCHORED = 1
STATE_ANCHORING = 2
STATE_ONLINE = 100
STATE_SHIELD_VULNERABLE = 110
STATE_SHIELD_REINFORCE = 111
STATE_ARMOR_VULNERABLE = 112
STATE_ARMOR_REINFORCE = 113
STATE_HULL_VULNERABLE = 114
OFFLINE_STATES = {STATE_UNKNOWN, STATE_UNANCHORED, STATE_ANCHORING}
DISABLED_STATES = {STATE_UNKNOWN,
 STATE_UNANCHORED,
 STATE_ANCHORING,
 STATE_ARMOR_REINFORCE,
 STATE_HULL_VULNERABLE}
STATES = {STATE_UNKNOWN: 'unknown',
 STATE_UNANCHORED: 'unanchored',
 STATE_ANCHORING: 'anchoring',
 STATE_ONLINE: 'online',
 STATE_SHIELD_VULNERABLE: 'shield_vulnerable',
 STATE_SHIELD_REINFORCE: 'shield_reinforce',
 STATE_ARMOR_VULNERABLE: 'armor_vulnerable',
 STATE_ARMOR_REINFORCE: 'armor_reinforce',
 STATE_HULL_VULNERABLE: 'hull_vulnerable'}
STATE_LABELS = {STATE_UNANCHORED: 'UI/Structures/States/Unanchored',
 STATE_ANCHORING: 'UI/Structures/States/Anchoring',
 STATE_ONLINE: 'UI/Structures/States/Online',
 STATE_SHIELD_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_SHIELD_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_ARMOR_VULNERABLE: 'UI/Structures/States/Vulnerable',
 STATE_ARMOR_REINFORCE: 'UI/Structures/States/Reinforced',
 STATE_HULL_VULNERABLE: 'UI/Structures/States/Vulnerable'}
STATE_SHIELD_ARMOR_HULL = {STATE_UNANCHORED: (1, 1, 1),
 STATE_ANCHORING: (0, 0, 1),
 STATE_ONLINE: (1, 1, 1),
 STATE_SHIELD_VULNERABLE: (1, 1, 1),
 STATE_SHIELD_REINFORCE: (0, 1, 1),
 STATE_ARMOR_VULNERABLE: (0, 1, 1),
 STATE_ARMOR_REINFORCE: (0, 0, 1),
 STATE_HULL_VULNERABLE: (0, 0, 1)}
STATE_VULNERABILITY = {STATE_UNANCHORED: False,
 STATE_ANCHORING: False,
 STATE_ONLINE: False,
 STATE_SHIELD_VULNERABLE: True,
 STATE_SHIELD_REINFORCE: False,
 STATE_ARMOR_VULNERABLE: True,
 STATE_ARMOR_REINFORCE: False,
 STATE_HULL_VULNERABLE: True}
STATE_CANCELS_UNANCHOR = {STATE_UNKNOWN: True,
 STATE_UNANCHORED: True,
 STATE_ANCHORING: True,
 STATE_ONLINE: False,
 STATE_SHIELD_VULNERABLE: False,
 STATE_SHIELD_REINFORCE: True,
 STATE_ARMOR_VULNERABLE: True,
 STATE_ARMOR_REINFORCE: True,
 STATE_HULL_VULNERABLE: True}
STATE_COLOR = {STATE_UNKNOWN: (0.0, 1.0, 1.0, 1.0),
 STATE_UNANCHORED: (0.0, 1.0, 1.0, 1.0),
 STATE_ANCHORING: (0.0, 1.0, 1.0, 1.0),
 STATE_ONLINE: (0.0, 1.0, 1.0, 1.0),
 STATE_SHIELD_VULNERABLE: (249 / 255.0,
                           179 / 255.0,
                           56 / 255.0,
                           1.0),
 STATE_SHIELD_REINFORCE: (0.0, 1.0, 1.0, 1.0),
 STATE_ARMOR_VULNERABLE: (249 / 255.0,
                          179 / 255.0,
                          56 / 255.0,
                          1.0),
 STATE_ARMOR_REINFORCE: (0.0, 1.0, 1.0, 1.0),
 STATE_HULL_VULNERABLE: (249 / 255.0,
                         179 / 255.0,
                         56 / 255.0,
                         1.0)}
DAY_MONDAY = 0
DAY_TUESDAY = 1
DAY_WEDNESDAY = 2
DAY_THURSDAY = 3
DAY_FRIDAY = 4
DAY_SATURDAY = 5
DAY_SUNDAY = 6
DAYS = (DAY_MONDAY,
 DAY_TUESDAY,
 DAY_WEDNESDAY,
 DAY_THURSDAY,
 DAY_FRIDAY,
 DAY_SATURDAY,
 DAY_SUNDAY)
REINFORCE_TIME_SHIELD = 86400
REINFORCE_TIME_ARMOR = 518400
REPAIR_TIMER = 900
ANCHORING_TIME = 86400
UNANCHORING_TIME = 604800
MIN_STRUCTURE_NAME_LEN = 3
