#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\script\mgt\fighterConst.py
MOVEMENT_COMMAND_ORBIT = 'ORBIT'
MOVEMENT_COMMAND_FOLLOW = 'FOLLOW'
MOVEMENT_COMMAND_STOP = 'STOP'
MOVEMENT_COMMAND_GOTO_POINT = 'GOTO_POINT'
COMMAND_ACTIVATE_ABILITY_SLOT_ON_POINT = 'ACTIVATE_ABILITY_SLOT_ON_POINT'
TUBE_STATE_EMPTY = 'EMPTY'
TUBE_STATE_LOADING = 'LOADING'
TUBE_STATE_READY = 'READY'
TUBE_STATE_UNLOADING = 'UNLOADING'
TUBE_STATE_LAUNCHING = 'LAUNCHING'
TUBE_STATE_INSPACE = 'INSPACE'
TUBE_STATE_RECALLING = 'RECALLING'
TUBE_STATE_LANDING = 'LANDING'
TUBE_STATE_REFUELLING = 'REFUELLING'
TUBE_STATES_INSPACE = [TUBE_STATE_LAUNCHING,
 TUBE_STATE_INSPACE,
 TUBE_STATE_RECALLING,
 TUBE_STATE_LANDING]
COLOR_RETURNING = (1.0, 0.93, 0.51)
COLOR_INSPACE = (0.46, 0.84, 1.0)
COLOR_OPEN = (0.62, 0.62, 0.62)
COLOR_READY = (0.52, 0.97, 0.34)
COLOR_BY_STATE = {TUBE_STATE_EMPTY: COLOR_OPEN,
 TUBE_STATE_LOADING: COLOR_OPEN,
 TUBE_STATE_READY: COLOR_READY,
 TUBE_STATE_UNLOADING: COLOR_OPEN,
 TUBE_STATE_LAUNCHING: COLOR_OPEN,
 TUBE_STATE_INSPACE: COLOR_INSPACE,
 TUBE_STATE_RECALLING: COLOR_RETURNING,
 TUBE_STATE_LANDING: COLOR_RETURNING,
 TUBE_STATE_REFUELLING: COLOR_RETURNING}
ROLE_NONE = 0
ROLE_ANTI_FIGHTER = 1
ROLE_GENERAL = 2
ROLE_EWAR = 3
ROLE_TORPEDO_BOMBER = 4
ROLE_AOE_BOMBER = 5
TEXTURE_BY_ROLE = {ROLE_NONE: None,
 ROLE_ANTI_FIGHTER: 'res:/UI/Texture/classes/ShipUI/Fighters/roleIcon_Interceptor.png',
 ROLE_GENERAL: 'res:/UI/Texture/classes/ShipUI/Fighters/roleIcon_General.png',
 ROLE_EWAR: 'res:/UI/Texture/classes/ShipUI/Fighters/roleIcon_Support.png',
 ROLE_TORPEDO_BOMBER: 'res:/UI/Texture/classes/ShipUI/Fighters/roleIcon_AntiCapital.png',
 ROLE_AOE_BOMBER: 'res:/UI/Texture/classes/ShipUI/Fighters/roleIcon_Bomber.png'}
HINTTEXT_BY_ROLE = {ROLE_NONE: 'UI/Inventory/Fighters/RoleNoneHint',
 ROLE_ANTI_FIGHTER: 'UI/Inventory/Fighters/RoleAntiFighterHint',
 ROLE_GENERAL: 'UI/Inventory/Fighters/RoleGeneralHint',
 ROLE_EWAR: 'UI/Inventory/Fighters/RoleEwarHint',
 ROLE_TORPEDO_BOMBER: 'UI/Inventory/Fighters/RoleTorpedoBomberHint',
 ROLE_AOE_BOMBER: 'UI/Inventory/Fighters/RoleAOEBomberHint'}
LABEL_BY_STATE = {TUBE_STATE_EMPTY: 'UI/Inventory/Fighters/Open',
 TUBE_STATE_LOADING: 'UI/Inventory/Fighters/Loading',
 TUBE_STATE_READY: 'UI/Inventory/Fighters/Ready',
 TUBE_STATE_UNLOADING: 'UI/Inventory/Fighters/Unloading',
 TUBE_STATE_LAUNCHING: 'UI/Inventory/Fighters/Launching',
 TUBE_STATE_INSPACE: 'UI/Inventory/Fighters/InSpace',
 TUBE_STATE_RECALLING: 'UI/Inventory/Fighters/Returning',
 TUBE_STATE_LANDING: 'UI/Inventory/Fighters/Landing',
 TUBE_STATE_REFUELLING: 'UI/Inventory/Fighters/Refuelling'}
HEALTHY_FIGHTER_SPACE = (0.83, 0.92, 1.0, 1.0)
HEALTHY_FIGHTER_TUBE = (0.47, 0.75, 0.26, 1.0)
DAMAGED_FIGHTER = (0.8, 0.0, 0.0, 1.0)
LOADING_FIGHTER = (0.47, 0.75, 0.26, 1.0)
DEAD_FIGHTER = (0, 0, 0, 1)
ABILITY_ATTACKTURRET = 1
ABILITY_WEBS = 2
ABILITY_TARGET_PAINT = 3
ABILITY_MICROWARPDRIVE = 4
ABILITY_MICRO_JUMP_DRIVE = 5
ABILITY_DAMAGE_BOOST = 6
ABILITY_LAUNCH_BOMB = 7
ABILITY_AFTERBURNER = 9
ABILITY_WARP_DISRUPT = 10
ABILITY_ENERGY_NEUT = 11
ABILITY_ECM = 12
ABILITY_EVASION = 13
ABILITY_MISSILE = 14
ABILITY_TACKLE = 16
ABILITY_ATTACKMISSILE = 17
ABILITY_TORPEDOSALVOEM = 18
ABILITY_TORPEDOSALVOTHERM = 19
ABILITY_TORPEDOSALVOKIN = 20
ABILITY_TORPEDOSALVOEXP = 21
ABILITY_PULSECANNON = 22
ABILITY_BEAMCANNON = 23
ABILITY_BLASTERCANNON = 24
ABILITY_RAILGUN = 25
ABILITY_AUTOCANNON = 26
ABILITY_ARTILLERY = 27
ABILITY_MICROMISSILESWARMEM = 29
ABILITY_MICROMISSILESWARMTHERM = 30
ABILITY_MICROMISSILESWARMKIN = 31
ABILITY_MICROMISSILESWARMEXP = 32
ABILITY_HEAVYROCKETSALVOEM = 33
ABILITY_HEAVYROCKETSALVOTHERM = 34
ABILITY_HEAVYROCKETSALVOKIN = 35
ABILITY_HEAVYROCKETSALVOEXP = 36
ABILITY_KAMIKAZE = 38
