#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\evecamera\__init__.py
PRIORITY_NONE = 0
PRIORITY_LOW = 1
PRIORITY_NORMAL = 2
PRIORITY_HIGH = 3
FOV_MIN = 0.05
FOV_MAX = 1.0
DEFAULT_MAX_SPEED = 0.07
DEFAULT_FRICTION = 7.0
DEFAULT_FRONT_CLIP = 6.0
DEFAULT_BACK_CLIP = 10000000.0
DEFAULT_IDLE_SCALE = 0.65
ORBIT_MOVE_DIST = 0.012
LOOKATRANGE_MAX = 100000.0
LOOKATRANGE_MAX_NEW = 10000000.0
CAM_SHIPORBIT = 'shiporbit'
CAM_SYSTEMMAP = 'systemmap'
CAM_STARMAP = 'starmap'
CAM_PLANET = 'planet'
CAM_HANGAR = 'hangar'
CAM_CAPITALHANGAR = 'capitalhangar'
CAM_TACTICAL = 'tactical'
CAM_SHIPPOV = 'pov'
CAM_JUMP = 'jump'
CAM_DEBUG = 'debug'
CAM_DEATHSCENE = 'deathscene'
CAM_LOGIN = 'login'
CAM_UNDOCK = 'undock'
CAM_ENTERSPACE = 'enterspace'
INSPACE_CAMERAS = (CAM_SHIPORBIT,
 CAM_TACTICAL,
 CAM_SHIPPOV,
 CAM_JUMP,
 CAM_DEATHSCENE,
 CAM_UNDOCK,
 CAM_ENTERSPACE)
