#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\sovDashboard\dashboardConst.py
STATUS_VULNERABLE = 0
STATUS_REINFORCED = 1
STATUS_INVULNERABLE = 2
STATUS_NODEFIGHT = 3
STATUS_VULNERABLE_OVERTIME = 4
PRIMARYCOLOR_DEFAULT = (0.8, 0.8, 0.8, 1.0)
COLOR_ATTACKING = (0.92, 0.14, 0.15, 1.0)
COLOR_ATTACKING_ODD = (0.6, 0.04, 0.05, 1.0)
COLOR_DEFENDING = (0.54, 0.83, 0.878, 1.0)
NO_STRUCTURE_ALPHA_BG = 0.5
NO_STRUCTURE_ALPHA = 0.25
UNCLAIMABLE = -1
PRIMARYCOLOR_BY_STATUS = {STATUS_VULNERABLE: PRIMARYCOLOR_DEFAULT,
 STATUS_VULNERABLE_OVERTIME: PRIMARYCOLOR_DEFAULT,
 STATUS_REINFORCED: (0.96, 0.57, 0.11, 1.0),
 STATUS_INVULNERABLE: PRIMARYCOLOR_DEFAULT,
 STATUS_NODEFIGHT: (0.92, 0.14, 0.15, 1.0)}
BGCOLOR_BY_STATUS = {STATUS_VULNERABLE: None,
 STATUS_VULNERABLE_OVERTIME: None,
 STATUS_REINFORCED: (0.96, 0.57, 0.11, 0.27),
 STATUS_INVULNERABLE: None,
 STATUS_NODEFIGHT: (0.92, 0.14, 0.15, 0.27)}
STRUCTURELABEL_BY_TYPEID = {const.typeTerritorialClaimUnit: 'UI/Sovereignty/TCU',
 const.typeInfrastructureHub: 'UI/Sovereignty/IHub',
 const.typeOutpostConstructionPlatform: 'UI/Sovereignty/Station'}
