#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\packages\carbonui\graphs\__init__.py
ANIM_NONE = 0
ANIM_BOTTOM_FROM_LEFT = 1
ANIM_BOTTOM_FROM_RIGHT = 2
ANIM_BOTTOM_RANDOM = 3
ANIM_BOTTOM_SIMULTANEOUS = 4
ANIM_TOP_FROM_LEFT = 5
ANIM_TOP_FROM_RIGHT = 6
ANIM_TOP_RANDOM = 7
ANIM_TOP_SIMULTANEOUS = 8
ANIM_CENTER_FROM_LEFT = 9
ANIM_CENTER_FROM_RIGHT = 10
ANIM_CENTER_FROM_RANDOM = 11
ANIM_CENTER_FROM_SIMULTANEOUS = 12
ANIM_FADE_IN = 13
ANIM_FADE_OUT = 14
