#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\script\dogma\pythonEffects\bastionMode.py
import dogma.const as dConst
from dogma.effects import Effect

class BaseBastionMode(Effect):
    __guid__ = 'dogmaXP.BastionMode'
    __effectIDs__ = [5788]
    isPythonEffect = True
    __modifier_only__ = True
    MODIFIER_CHANGES = [(dConst.dgmAssPostAssignment, dConst.attributeMaxLockedTargets, dConst.attributeMaxLockedTargets),
     (dConst.dgmAssPreMul, dConst.attributeScanResolution, dConst.attributeScanResolutionMultiplier),
     (dConst.dgmAssPostPercent, dConst.attributeMaxVelocity, dConst.attributeSpeedFactor),
     (dConst.dgmAssModAdd, dConst.attributeWarpScrambleStatus, dConst.attributeSiegeModeWarpStatus),
     (dConst.dgmAssPostMul, dConst.attributeMass, dConst.attributeSiegeMassMultiplier),
     (dConst.dgmAssPostAssignment, dConst.attributeDisallowOffensiveModifiers, dConst.attributeDisallowOffensiveModifiers),
     (dConst.dgmAssPreMul, dConst.attributeArmorEmDamageResonance, dConst.attributeArmorEmDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeArmorExplosiveDamageResonance, dConst.attributeArmorExplosiveDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeArmorKineticDamageResonance, dConst.attributeArmorKineticDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeArmorThermalDamageResonance, dConst.attributeArmorThermalDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeEmDamageResonance, dConst.attributeHullEmDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeExplosiveDamageResonance, dConst.attributeHullExplosiveDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeKineticDamageResonance, dConst.attributeHullKineticDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeThermalDamageResonance, dConst.attributeHullThermalDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeShieldEmDamageResonance, dConst.attributeShieldEmDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeShieldExplosiveDamageResonance, dConst.attributeShieldExplosiveDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeShieldKineticDamageResonance, dConst.attributeShieldKineticDamageResonance),
     (dConst.dgmAssPreMul, dConst.attributeShieldThermalDamageResonance, dConst.attributeShieldThermalDamageResonance)]
    SKILL_MODIFIER_CHANGES_FOR_LOCATION = [(dConst.dgmAssPostPercent,
      21803,
      dConst.attributeArmorDamageAmount,
      dConst.attributeArmorDamageAmountBonus),
     (dConst.dgmAssPostPercent,
      21803,
      dConst.attributeDuration,
      dConst.attributeArmorDamageDurationBonus),
     (dConst.dgmAssPostPercent,
      21802,
      dConst.attributeShieldBonus,
      dConst.attributeShieldBoostMultiplier),
     (dConst.dgmAssPostPercent,
      21802,
      dConst.attributeDuration,
      dConst.attributeShieldBonusDurationBonus),
     (dConst.dgmAssPostPercent,
      21666,
      dConst.attributeDamageMultiplier,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21666,
      dConst.attributeTrackingSpeed,
      dConst.attributeTrackingSpeedBonus),
     (dConst.dgmAssPostPercent,
      20327,
      dConst.attributeDamageMultiplier,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      20327,
      dConst.attributeTrackingSpeed,
      dConst.attributeTrackingSpeedBonus),
     (dConst.dgmAssPostPercent,
      21667,
      dConst.attributeDamageMultiplier,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21667,
      dConst.attributeTrackingSpeed,
      dConst.attributeTrackingSpeedBonus),
     (dConst.dgmAssPostPercent,
      3309,
      dConst.attributeMaxRange,
      dConst.attributeMaxRangeBonus),
     (dConst.dgmAssPostPercent,
      3307,
      dConst.attributeMaxRange,
      dConst.attributeMaxRangeBonus),
     (dConst.dgmAssPostPercent,
      3308,
      dConst.attributeMaxRange,
      dConst.attributeMaxRangeBonus),
     (dConst.dgmAssPostPercent,
      3309,
      dConst.attributeFalloff,
      dConst.attributeFalloffBonus),
     (dConst.dgmAssPostPercent,
      3307,
      dConst.attributeFalloff,
      dConst.attributeFalloffBonus),
     (dConst.dgmAssPostPercent,
      3308,
      dConst.attributeFalloff,
      dConst.attributeFalloffBonus),
     (dConst.dgmAssPostPercent,
      3393,
      dConst.attributeArmorDamageAmount,
      dConst.attributeArmorDamageAmountBonus),
     (dConst.dgmAssPostPercent,
      3416,
      dConst.attributeShieldBonus,
      dConst.attributeShieldBoostMultiplier),
     (dConst.dgmAssModAdd,
      4385,
      dConst.attributeActivationBlocked,
      dConst.attributeActivationBlockedStrenght)]
    SKILL_MODIFER_CHANGES_FOR_OWNER = [(dConst.dgmAssPostPercent,
      3324,
      dConst.attributeMaxVelocity,
      dConst.attributeMissileVelocityBonus),
     (dConst.dgmAssPostPercent,
      32435,
      dConst.attributeAoeVelocity,
      dConst.attributeAoeVelocityBonus),
     (dConst.dgmAssPostPercent,
      32435,
      dConst.attributeKineticDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      32435,
      dConst.attributeEmDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      32435,
      dConst.attributeExplosiveDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeEmDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeExplosiveDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeKineticDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeThermalDamage,
      dConst.attributeDamageMultiplierBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeAoeVelocity,
      dConst.attributeAoeVelocityBonus),
     (dConst.dgmAssPostPercent,
      21668,
      dConst.attributeAoeFalloff,
      dConst.attributeAoeFalloffBonus),
     (dConst.dgmAssPostPercent,
      3325,
      dConst.attributeMaxVelocity,
      dConst.attributeMissileVelocityBonus),
     (dConst.dgmAssPostPercent,
      3326,
      dConst.attributeMaxVelocity,
      dConst.attributeMissileVelocityBonus)]

    def Start(self, env, dogmaLM, itemID, shipID, charID, otherID, targetID):
        self.AddOwnerRequiredSkillModifiers(dogmaLM, ownerID=charID, fromItemID=env.itemID)
        self.AddModifiers(dogmaLM, toItemID=shipID, fromItemID=itemID)
        self.AddLocationRequiredSkillModifiers(dogmaLM, toLocationID=shipID, fromItemID=env.itemID)

    def Stop(self, env, dogmaLM, itemID, shipID, charID, otherID, targetID):
        self.RemoveOwnerRequiredSkillModifiers(dogmaLM, charID, env.itemID)
        self.RemoveModifiers(dogmaLM, shipID, itemID)
        self.RemoveLocationRequiredSkillModifiers(dogmaLM, shipID, env.itemID)

    RestrictedStop = Stop
