#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\paperDoll\statistics.py
from eve.client.script.paperDoll.paperDollStatistics import CST_COUNTER_HIGH
from eve.client.script.paperDoll.paperDollStatistics import CST_COUNTER_LOW
from eve.client.script.paperDoll.paperDollStatistics import CST_MEMORY
from eve.client.script.paperDoll.paperDollStatistics import CST_TIME
from eve.client.script.paperDoll.paperDollStatistics import CreateOrGetStatistic
from eve.client.script.paperDoll.paperDollStatistics import GetTimeDiffInSeconds
from eve.client.script.paperDoll.paperDollStatistics import Reset
from eve.client.script.paperDoll.paperDollStatistics import compositeTime
from eve.client.script.paperDoll.paperDollStatistics import mapsComposited
from eve.client.script.paperDoll.paperDollStatistics import updateCount
from eve.client.script.paperDoll.paperDollStatistics import updateTime
