#Embedded file name: e:\jenkins\workspace\client_SERENITY\branches\release\SERENITY\eve\common\modules\nice\client\_nastyspace\paperDoll\testing.py
from eve.client.script.paperDoll.paperDollTests import BenchmarkTest
from eve.client.script.paperDoll.paperDollTests import Benchmarker
from eve.client.script.paperDoll.paperDollTests import CollectCharacterSelectionPaths
from eve.client.script.paperDoll.paperDollTests import CreateEmptyScene
from eve.client.script.paperDoll.paperDollTests import DEFAULT_PREPASS_RENDERJOB_NAME
from eve.client.script.paperDoll.paperDollTests import MultiDollTest
from eve.client.script.paperDoll.paperDollTests import PerformanceTestResults
from eve.client.script.paperDoll.paperDollTests import RunClothedSpawnTest
from eve.client.script.paperDoll.paperDollTests import RunComprehensiveSymmetricalDollLODTest
from eve.client.script.paperDoll.paperDollTests import RunCrowdSpawnTest
from eve.client.script.paperDoll.paperDollTests import RunIncarnaCrowdTest
from eve.client.script.paperDoll.paperDollTests import RunSymmetricalSingleClothedDollLODTest
from eve.client.script.paperDoll.paperDollTests import RunSymmetricalSingleDollLODTest
from eve.client.script.paperDoll.paperDollTests import RunSymmetricalSingleNudeLODTest
from eve.client.script.paperDoll.paperDollTests import SetupScene
from eve.client.script.paperDoll.paperDollTests import SingleDollTest
from eve.client.script.paperDoll.paperDollTests import lock
